<a href="https://colab.research.google.com/github/ishaangign/QR_codeinJS/blob/main/Major_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df=pd.read_csv('tested.csv')
df

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
df=df.dropna()

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
dict = {"female":0,"male":1}
df["male"] = df["Sex"].map(dict)
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


PassengerId  Survived  Pclass  \
12           904         1       1   
14           906         1       1   
24           916         1       1   
26           918         1       1   
28           920         0       1   
..           ...       ...     ...   
404         1296         0       1   
405         1297         0       2   
407         1299         0       1   
411         1303         1       1   
414         1306         1       1   

                                                  Name     Sex   Age  SibSp  \
12       Snyder, Mrs. John Pillsbury (Nelle Stevenson)  female  23.0      1   
14   Chaffee, Mrs. Herbert Fuller (Carrie Constance...  female  47.0      1   
24     Ryerson, Mrs. Arthur Larned (Emily Maria Borie)  female  48.0      1   
26                        Ostby, Miss. Helene Ragnhild  female  22.0      0   
28                             Brady, Mr. John Bertram    male  41.0      0   
..                                                 ...     ...   ...    ...   
404                       Frauenthal, Mr. Isaac Gerald    male  43.0      1   
405       Nourney, Mr. Alfred (Baron von Drachstedt")"    male  20.0      0   
407                         Widener, Mr. George Dunton    male  50.0      1   
411    Minahan, Mrs. William Edward (Lillian E Thorpe)  female  37.0      1   
414                       Oliva y Ocana, Dona. Fermina  female  39.0      0   

     Parch         Ticket      Fare            Cabin Embarked  male  
12       0          21228   82.2667              B45        S     0  
14       0    W.E.P. 5734   61.1750              E31        S     0  
24       3       PC 17608  262.3750  B57 B59 B63 B66        C     0  
26       1         113509   61.9792              B36        C     0  
28       0         113054   30.5000              A21        S     1  
..     ...            ...       ...              ...      ...   ...  
404      0          17765   27.7208              D40        C     1  
405      0  SC/PARIS 2166   13.8625              D38        C     1  
407      1         113503  211.5000              C80        C     1  
411      0          19928   90.0000              C78        Q     0  
414      0       PC 17758  108.9000             C105        C     0  

[87 rows x 13 columns]

In [ ]:
x = df.iloc[:,[2,5,6,7,9,12]].values
x

array([[  1.    ,  23.    ,   1.    ,   0.    ,  82.2667,   0.    ],
       [  1.    ,  47.    ,   1.    ,   0.    ,  61.175 ,   0.    ],
       [  1.    ,  48.    ,   1.    ,   3.    , 262.375 ,   0.    ],
       [  1.    ,  22.    ,   0.    ,   1.    ,  61.9792,   0.    ],
       [  1.    ,  41.    ,   0.    ,   0.    ,  30.5   ,   1.    ],
       [  1.    ,  30.    ,   1.    ,   0.    ,  57.75  ,   1.    ],
       [  1.    ,  45.    ,   1.    ,   0.    ,  52.5542,   0.    ],
       [  1.    ,  45.    ,   0.    ,   0.    ,  29.7   ,   1.    ],
       [  1.    ,  60.    ,   0.    ,   0.    ,  76.2917,   0.    ],
       [  1.    ,  24.    ,   1.    ,   0.    ,  60.    ,   1.    ],
       [  1.    ,  28.    ,   3.    ,   2.    , 263.    ,   0.    ],
       [  3.    ,  25.    ,   0.    ,   0.    ,   7.65  ,   1.    ],
       [  1.    ,  36.    ,   0.    ,   0.    , 262.375 ,   0.    ],
       [  1.    ,  13.    ,   2.    ,   2.    , 262.375 ,   1.    ],
       [  1.    ,  31.    ,   0.  

In [ ]:
y = df.iloc[:,1].values
y

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 0)

In [ ]:
print(x.shape)
print(x_train.shape)
print(x_test.shape)

(87, 6)
(65, 6)
(22, 6)


In [ ]:
print(y.shape)
print(y_train.shape)
print(y_test.shape)

(87,)
(65,)
(22,)


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)


In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1])

In [ ]:
y_test

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)*100

100.0

In [ ]:
from sklearn import svm
clf = svm.SVC()


In [ ]:
clf.fit(x_train,y_train)

SVC()

In [ ]:
y_pred = clf.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1])

In [ ]:
y_test

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)*100

95.45454545454545